"""
Django settings for db_backup project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$65km__l!h&)fwh946t03=uoz-=ywf3e_f81uhd(d+hve59%c#"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'blog',
    'dbbackup',
    'django_apscheduler',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "db_backup.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "db_backup.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'dbbackup',
        'USER': 'postgres',
        'PASSWORD': 'admin',
        'HOST': 'localhost',  
        'PORT': 5432
    }
}


# for production
DBBACKUP_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
DBBACKUP_STORAGE_OPTIONS = {
        'access_key': 'your_access_key',
        'secret_key': 'your_secret_key',
        'bucket_name': 'bucket_name',
        'default_acl': 'private',
        'endpoint_url': 'endpoint_url',
        'location': 'exaple-dir'
}

import os  # if not yet imported

DBBACKUP_CONNECTORS = {
    'default': {
        'USER': 'postgres',      # Optional: Use a different user for backups
        'PASSWORD': 'admin',  # Optional: Backup user password
        'HOST': 'localhost',      # Optional: Use a different host for backup
        'CONNECTOR': 'dbbackup.db.postgresql.PgDumpConnector',  # Use PgDumpConnector or PgDumpBinaryConnector
        'DUMP_CMD': 'C:/Program Files/PostgreSQL/17/bin/pg_dump.exe',  # Full path to pg_dump on Windows
        'RESTORE_CMD': 'C:/Program Files/PostgreSQL/17/bin/psql.exe',  # Full path to psql on Windows
        'SINGLE_TRANSACTION': True,      # Optional: Wrap restores in single transaction
        'DROP': True,                    # Drop existing tables before restore
        'EXTENSION': 'dump',             # Extension of the backup file
    }
}


DBBACKUP_HOSTNAME = 'universalml'
DBBACKUP_CLEANUP_KEEP = 3

# for local development
# DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
# DBBACKUP_STORAGE_OPTIONS = {'location': BASE_DIR / 'backup'}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
